output instance_public_ips {
    value = [oci_core_instance.tutorial_instance.*.public_ip] 
}

### Important Security Notice ###
# The private key generated by this resource will be stored unencrypted in your Terraform state file. 
# Use of this resource for production deployments is not recommended. 
# Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run.
output "generated_private_key_pem" {
  value = tls_private_key.compute_ssh_key.private_key_pem
}